
name: coverage

on:
  push:
    branches:
      - master
  pull_request:

env:
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run coverage testing
      run: make docker-runtest-coverage
